import React from 'react';
import { AlertCircle } from 'lucide-react';

export const Disclaimer: React.FC = () => {
  return (
    <div style={{
      background: 'rgba(30, 41, 59, 0.4)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      borderRadius: 'var(--radius-md)',
      padding: '1rem 1.25rem',
      display: 'flex',
      alignItems: 'flex-start',
      gap: '0.8rem',
      fontSize: '0.8rem',
      color: 'var(--text-subtle)',
      lineHeight: 1.4,
    }}>
      <AlertCircle size={18} color="var(--accent-cyan)" style={{ marginTop: '2px', flexShrink: 0 }} />
      <div>
        <strong style={{ color: 'var(--text-muted)' }}>Regulatory & Clinical Disclaimer: </strong>
        NeoHealth AI is designed exclusively as an educational decision-support & preliminary triage aid. Results generated by deep neural network models do not constitute a definitive medical diagnosis, pathology report, or treatment plan. Always consult a qualified dermatologist or medical practitioner for formal clinical evaluation and dermoscopic biopsy.
      </div>
    </div>
  );
};
